sudo: true

language: node_js

node_js: "6"

script: 
- npm test

before_script: 
  - psql -c 'create database document_ms_test;' -U postgres
  - npm i -g sequelize-cli
  - sequelize db:migrate --env=test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls.js

after_success:
  - npm run coverage

services:
  - postgresql